%[text] ## 创建者：林宸曳LuCkY，2025RM，平步电控
%[text] 这一篇是直接解上交建模最后的五个方程得到的结果，与马老师建模版有一定区别，都能使用。
%[text] 主要还是看另一篇，也就是BalanceSoldier\_LQR\_ABMatrix.mlx
clear;
clc;

%-----------------运动学变量-------------------%
syms theta_wl theta_wr theta_dot_wl theta_dot_wr theta_ddot_wl theta_ddot_wr
syms theta_ll(t) theta_lr(t) theta_b(t) phi(t) s(t) 

%-----------------动力学变量-------------------%
syms T_wl T_wr T_bl T_br

%-----------------参数-------------------%
syms l_l  l_r
% syms R_w  R_l 
% syms m_w m_l m_b  I_w I_ll I_lr I_b I_z  l_c  g

R_w = 0.06;     R_l = 0.2655;
m_b = 12.5;     m_l = 1.72;    m_w = 1.2;
I_z = 0.656283; l_c = 0.021;     g = 9.8;

l_wl = l_l/2;  l_wr = l_r/2;  % 轮轴到腿质心距离（质心认为是几何中心）
l_bl = l_l/2;  l_br = l_r/2;  % 腿质心到髋部距离（质心认为是几何中心）
I_b = m_b*(0.3^2+0.12^2)/12.0;
I_ll = m_l*( (l_l)^2+0.05^2 )/12.0;%腿部转动惯量1/12*m*L²
I_lr = m_l*( (l_r)^2+0.05^2 )/12.0;%腿部转动惯量1/12*m*L²
I_w = 1/2*m_w*R_w^2; %把轮子视为圆柱体，转动惯量为1/2*质量*半径²（马老师这里没有1/2）
%[text] 
% 2.1：水平位移 = 轮子半径*轮转角
eqn1 = s == R_w*(theta_wl+theta_wr)/2;

%{
% 2.5 2.6（由这两个方程推出2.7 2.8）
% 移项后
% 机体质心水平位移 = 轮半径*左轮转角 + 轮距/2*Yaw + 腿长*sin（腿部夹角）
% 机体质心水平位移 = 轮半径*右轮转角 - 轮距/2*Yaw + 腿长*sin（腿部夹角）
syms s_b
Temp_equ25 = R_w*theta_wl == s_b - R_l*phi - Leg_length_l*sin(theta_ll); 
Temp_equ26 = R_w*theta_wr == s_b + R_l*phi - Leg_length_r*sin(theta_lr);
[s_b,phi] = solve(Temp_equ25,Temp_equ26,s_b,yaw)
%}

% 联立2.5 2.6解得2.7 2.8
% 2.7 phi(偏航角yaw)
eqn2 = phi == R_w/(2*R_l)*(theta_wr-theta_wl)...
            - l_l/(2*R_l)*sin(theta_ll)...
            + l_r/(2*R_l)*sin(theta_lr);

[theta_wl,theta_wr] = solve(eqn1,eqn2,theta_wl,theta_wr);
% 2.8 s_b
s_b = R_w/2*(theta_wl+theta_wr) ...
    + l_l/2*sin(theta_ll)...
    + l_r/2*sin(theta_lr);

% 2.9 速度 = 轮半径 * 轮速度 (对2.1求一导)
eqn3 = diff(s,t,1) == R_w/2*(theta_dot_wl + theta_dot_wr);

% 2.11 偏航角速度 (对2.7求一导)
eqn4 = diff(phi,t,1) == R_w/(2*R_l)*(theta_dot_wr - theta_dot_wl)...
                -l_l/(2*R_l)*cos(theta_ll)*diff(theta_ll,t,1)...
                +l_r/(2*R_l)*cos(theta_lr)*diff(theta_lr,t,1);

[theta_dot_wl,theta_dot_wr] = solve(eqn3,eqn4,theta_dot_wl,theta_dot_wr);
% 2.10 加速度 = 轮半径 * 轮加速度 (对2.1求二导)
eqn5 = diff(s,t,2) == R_w/2*(theta_ddot_wl + theta_ddot_wr);

% 2.12 偏航角加速度 (对2.7求二导)
eqn6 = diff(phi,t,2) == R_w/(2*R_l)*(theta_ddot_wr - theta_ddot_wl) ...
                       - l_l/(2*R_l)*cos(theta_ll)*diff(theta_ll,t,2) ...
                       + l_r/(2*R_l)*cos(theta_lr)*diff(theta_lr,t,2) ...
                       + l_l/(2*R_l)*sin(theta_ll)*(diff(theta_ll,t,1))^2 ...
                       - l_r/(2*R_l)*sin(theta_lr)*(diff(theta_lr,t,1))^2;

[theta_ddot_wl,theta_ddot_wr] = solve(eqn5,eqn6,theta_ddot_wl,theta_ddot_wr);
%[text] 
syms s_ddot s_dot phi_ddot phi_dot theta_ddot_b theta_dot_b
syms theta_ddot_ll theta_dot_ll theta_ddot_lr theta_dot_lr
syms s0 phi0 theta_ll0 theta_lr0 theta_b0 
%[text] 
equ3_11 = (I_w*l_l/R_w + m_w*R_w*l_l+m_l*R_w*l_bl)*theta_ddot_wl ...
        + (m_l*l_wl* l_bl-I_ll )*theta_ddot_ll+(m_l*l_wl+1/2*m_b*l_l)*g*theta_ll+T_bl  -(1+l_l/R_w)*T_wl==0;
equ3_12 = (I_w*l_r/R_w + m_w*R_w*l_r+m_l*R_w*l_br)*theta_ddot_wr+(m_l*l_wr* l_br-I_lr )*theta_ddot_lr+(m_l*l_wr+1/2*m_b*l_r )*g*theta_lr+T_br  -(1+l_r/R_w )*T_wr==0;
equ3_13 = -(m_w*R_w^2+I_w+ m_l*R_w^2+1/2*m_b*R_w^2)*theta_ddot_wl-(m_w*R_w^2+I_w+m_l*R_w^2+1/2*m_b*R_w^2 )*theta_ddot_wr-(m_l*R_w*l_wl+1/2*m_b*R_w*l_l )*theta_ddot_ll-(m_l*R_w*l_wr+1/2*m_b*R_w*l_r)*theta_ddot_lr+ T_wl+T_wr==0;
equ3_14 = (m_w*R_w*l_c+I_w*l_c/R_w+m_l*R_w*l_c)*theta_ddot_wl+(m_w*R_w*l_c+I_w*l_c/R_w + m_l*R_w*l_c )*theta_ddot_wr+(l_c*m_l*l_wl )*theta_ddot_ll+(l_c*m_l*l_wr )*theta_ddot_lr-I_b*theta_ddot_b+(m_b*g*l_c*theta_b)-l_c/R_w *(T_wl+T_wr )-(T_br+ T_bl)==0;
% 上式为上交化简，下为我自己化不动了的
%equ3_14L = (m_w*R_w*l_c+I_w*l_c/R_w+m_l*R_w*l_c)*theta_ddot_wl+(m_w*R_w*l_c+I_w*l_c/R_w + m_l*R_w*l_c )*theta_ddot_wr+(l_c*m_l*l_wl )*theta_ddot_ll+(l_c*m_l*l_wr )*theta_ddot_lr-I_b*theta_ddot_b+(-l_c*pitch_b*g*m_l*((l_wl)/l_l+l_wr/l_r))-l_c/R_w *(T_wl+T_wr )-(T_br+ T_bl)==0;
equ3_15 = (1/2*I_z*R_w/R_l +I_w*R_l/R_w )*theta_ddot_wl-(1/2*I_z*R_w/R_l +I_w*R_l/R_w )*theta_ddot_wr+1/2*I_z*l_l/R_l *theta_ddot_ll-1/2*I_z*l_r/R_l *theta_ddot_lr-T_wl*R_l/R_w +T_wr*R_l/R_w == 0;

% 把导数全部换成单独的变量，几个关于时间的变量换成单独变量
equ3_11 = subs(equ3_11, ...
    {diff(s,t,2),       diff(s,t,1),        diff(phi,t,2),      diff(phi,t,1), ...
    diff(theta_ll,t,2), diff(theta_ll,t,1), diff(theta_lr,t,2), diff(theta_lr,t,1) ...
    diff(theta_b,t,2),  diff(theta_b,t,1),  s,                  phi, ...
    theta_ll,           theta_lr,           theta_b}, ...
    ...
    {s_ddot,            s_dot,              phi_ddot,           phi_dot, ...
    theta_ddot_ll,      theta_dot_ll,       theta_ddot_lr,      theta_dot_lr, ...
    theta_ddot_b,       theta_dot_b,        s0,                 phi0, ...
    theta_ll0,          theta_lr0,          theta_b0});

equ3_12 = subs(equ3_12, ...
    {diff(s,t,2),       diff(s,t,1),        diff(phi,t,2),      diff(phi,t,1), ...
    diff(theta_ll,t,2), diff(theta_ll,t,1), diff(theta_lr,t,2), diff(theta_lr,t,1) ...
    diff(theta_b,t,2),  diff(theta_b,t,1),  s,                  phi, ...
    theta_ll,           theta_lr,           theta_b}, ...
    ...
    {s_ddot,            s_dot,              phi_ddot,           phi_dot, ...
    theta_ddot_ll,      theta_dot_ll,       theta_ddot_lr,      theta_dot_lr, ...
    theta_ddot_b,       theta_dot_b,        s0,                 phi0, ...
    theta_ll0,          theta_lr0,          theta_b0});

equ3_13 = subs(equ3_13, ...
    {diff(s,t,2),       diff(s,t,1),        diff(phi,t,2),      diff(phi,t,1), ...
    diff(theta_ll,t,2), diff(theta_ll,t,1), diff(theta_lr,t,2), diff(theta_lr,t,1) ...
    diff(theta_b,t,2),  diff(theta_b,t,1),  s,                  phi, ...
    theta_ll,           theta_lr,           theta_b}, ...
    ...
    {s_ddot,            s_dot,              phi_ddot,           phi_dot, ...
    theta_ddot_ll,      theta_dot_ll,       theta_ddot_lr,      theta_dot_lr, ...
    theta_ddot_b,       theta_dot_b,        s0,                 phi0, ...
    theta_ll0,          theta_lr0,          theta_b0});

equ3_14 = subs(equ3_14, ...
    {diff(s,t,2),       diff(s,t,1),        diff(phi,t,2),      diff(phi,t,1), ...
    diff(theta_ll,t,2), diff(theta_ll,t,1), diff(theta_lr,t,2), diff(theta_lr,t,1) ...
    diff(theta_b,t,2),  diff(theta_b,t,1),  s,                  phi, ...
    theta_ll,           theta_lr,           theta_b}, ...
    ...
    {s_ddot,            s_dot,              phi_ddot,           phi_dot, ...
    theta_ddot_ll,      theta_dot_ll,       theta_ddot_lr,      theta_dot_lr, ...
    theta_ddot_b,       theta_dot_b,        s0,                 phi0, ...
    theta_ll0,          theta_lr0,          theta_b0});

equ3_15 = subs(equ3_15, ...
    {diff(s,t,2),       diff(s,t,1),        diff(phi,t,2),      diff(phi,t,1), ...
    diff(theta_ll,t,2), diff(theta_ll,t,1), diff(theta_lr,t,2), diff(theta_lr,t,1) ...
    diff(theta_b,t,2),  diff(theta_b,t,1),  s,                  phi, ...
    theta_ll,           theta_lr,           theta_b}, ...
    ...
    {s_ddot,            s_dot,              phi_ddot,           phi_dot, ...
    theta_ddot_ll,      theta_dot_ll,       theta_ddot_lr,      theta_dot_lr, ...
    theta_ddot_b,       theta_dot_b,        s0,                 phi0, ...
    theta_ll0,          theta_lr0,          theta_b0});


[s_ddot,phi_ddot,theta_ddot_ll,theta_ddot_lr,theta_ddot_b] ...
= solve(equ3_11,equ3_12,equ3_13,equ3_14,equ3_15, s_ddot,phi_ddot,theta_ddot_ll,theta_ddot_lr,theta_ddot_b);

A = jacobian([s_dot,s_ddot,phi_dot,phi_ddot,theta_dot_ll,theta_ddot_ll,theta_dot_lr,theta_ddot_lr,theta_dot_b,theta_ddot_b], ...
             [s0,   s_dot, phi0,   phi_dot, theta_ll0,   theta_dot_ll, theta_lr0,   theta_dot_lr, theta_b0,   theta_dot_b]);

B = jacobian([s_dot,s_ddot,phi_dot,phi_ddot,theta_dot_ll,theta_ddot_ll,theta_dot_lr,theta_ddot_lr,theta_dot_b,theta_ddot_b], ...
             [T_wl,T_wr,T_bl,T_br]);

A = subs(A,{s_dot, phi_dot, theta_ll0, theta_dot_ll, theta_lr0, theta_dot_lr, ...
            theta_b0, theta_dot_b, T_wl, T_wr, T_bl, T_br}, ...
           {0,0,0,0,0,0,0,0,0,0,0,0});

B = subs(B,{s_dot, phi_dot, theta_ll0, theta_dot_ll, theta_lr0, theta_dot_lr, ...
            theta_b0, theta_dot_b, T_wl, T_wr, T_bl, T_br}, ...
           {0,0,0,0,0,0,0,0,0,0,0,0});

%假设腿长为0.18m代入计算
% A = double(subs(A,{l_l,l_r},{0.18,0.18})) %[output:521c6130]
% B = double(subs(B,{l_l,l_r},{0.18,0.18})) %[output:35a29f45]

%[appendix]{"version":"1.0"}
%---
%[metadata:view]
%   data: {"layout":"onright","rightPanelPercent":4.2}
%---
%[output:521c6130]
%   data: {"dataType":"matrix","outputData":{"columns":10,"name":"A","rows":10,"type":"double","value":[["0","1.0000","0","0","0","0","0","0","0","0"],["0","0","0","0","-15.2717","0","-15.2717","0","0","0"],["0","0","0","1.0000","0","0","0","0","0","0"],["0","0","0","0","-7.2005","0","7.2005","0","0","0"],["0","0","0","0","0","1.0000","0","0","0","0"],["0","0","0","0","209.6061","0","23.5620","0","0","0"],["0","0","0","0","0","0","0","1.0000","0","0"],["0","0","0","0","23.5620","0","209.6061","0","0","0"],["0","0","0","0","0","0","0","0","0","1.0000"],["0","0","0","0","-13.7911","0","-13.7911","0","23.6552","0"]]}}
%---
%[output:35a29f45]
%   data: {"dataType":"matrix","outputData":{"columns":4,"name":"B","rows":10,"type":"double","value":[["0","0","0","0"],["4.7290","4.7290","-1.2176","-1.2176"],["0","0","0","0"],["-4.5481","4.5481","-0.5741","0.5741"],["0","0","0","0"],["-47.9942","-11.1847","16.7123","1.8786"],["0","0","0","0"],["-11.1847","-47.9942","1.8786","16.7123"],["0","0","0","0"],["1.4414","1.4414","-10.2950","-10.2950"]]}}
%---
